labels: [discussion, general]
body:
  - type: markdown
    attributes:
      value: |
        欢迎参与开放性讨论！这里适合社区交流、项目发展讨论和其他相关话题。
        
        > 💬 **提示**: 保持友善和建设性，尊重不同观点
  
  - type: textarea
    id: discussion-topic
    attributes:
      label: 💬 讨论主题
      description: 简要说明您想讨论的主题
      placeholder: 一句话概括您想讨论的内容...
    validations:
      required: true
  
  - type: dropdown
    id: discussion-type
    attributes:
      label: 🏷️ 讨论类型
      description: 选择最符合的讨论类型
      options:
        - 项目发展方向
        - 社区建设和治理
        - 技术趋势和展望
        - 用户体验和反馈
        - 文档和教程改进
        - 最佳实践分享
        - 开源协作讨论
        - 功能规划和路线图
        - 社区活动和倡议
        - 其他开放性话题
    validations:
      required: true
  
  - type: textarea
    id: background
    attributes:
      label: 📋 背景信息
      description: 提供必要的背景信息和上下文
      placeholder: |
        请描述：
        - 讨论的背景和起因
        - 相关的项目现状
        - 为什么这个话题重要
        - 当前面临的挑战或机会
    validations:
      required: true
  
  - type: textarea
    id: main-content
    attributes:
      label: 📝 详细内容
      description: 详细阐述您的观点、想法或要讨论的问题
      placeholder: |
        请详细描述：
        - 您的观点和看法
        - 要讨论的具体问题
        - 相关的经验和案例
        - 希望探讨的方向
    validations:
      required: true
  
  - type: dropdown
    id: discussion-goal
    attributes:
      label: 🎯 讨论目标
      description: 您希望通过这次讨论达到什么目的？
      options:
        - 收集社区意见和建议
        - 分享经验和最佳实践
        - 寻求技术指导和帮助
        - 讨论项目发展方向
        - 建立共识和标准
        - 发现合作机会
        - 解决分歧或争议
        - 教育和知识分享
        - 其他目标
    validations:
      required: true
  
  - type: textarea
    id: key-questions
    attributes:
      label: ❓ 核心问题
      description: 列出您希望讨论的核心问题
      placeholder: |
        请列出要讨论的关键问题：
        1. 
        2. 
        3. 
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  
  - type: checkboxes
    id: target-audience
    attributes:
      label: 👥 目标参与者
      description: 您希望哪些人参与这个讨论？
      options:
        - label: 项目维护者和核心贡献者
        - label: 有经验的用户和专家
        - label: 新手用户和初学者
        - label: 开发者和技术人员
        - label: 文档和内容贡献者
        - label: 社区管理者和组织者
        - label: 所有感兴趣的社区成员
  
  - type: textarea
    id: current-situation
    attributes:
      label: 📊 现状分析
      description: 分析当前的情况、趋势或挑战
      placeholder: |
        请分析：
        - 当前的情况如何？
        - 存在哪些问题或挑战？
        - 有什么机会或优势？
        - 相关的趋势和变化
  
  - type: textarea
    id: references
    attributes:
      label: 📚 参考资料
      description: 提供相关的资料、链接或参考资源
      placeholder: |
        - 相关文档和资料链接
        - 类似项目的案例
        - 行业报告或研究
        - 有用的工具和资源
  
  - type: textarea
    id: proposed-approach
    attributes:
      label: 💡 初步想法
      description: 分享您对这个话题的初步观点或建议
      placeholder: |
        请分享：
        - 您的初步想法和观点
        - 可能的解决方案或方向
        - 值得考虑的因素
        - 需要避免的误区
  
  - type: checkboxes
    id: discussion-guidelines
    attributes:
      label: 📋 讨论规则
      description: 请确认遵守以下讨论规则
      options:
        - label: 我将保持友善和尊重的态度
          required: true
        - label: 我接受不同的观点和意见
          required: true
        - label: 我将基于事实进行讨论
          required: true
        - label: 我会建设性地提出意见
          required: true
        - label: 我承诺避免人身攻击和不当言论
          required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: 📝 补充信息
      description: 其他相关的信息或想要补充的内容
      placeholder: |
        - 时间敏感性（是否有截止日期）
        - 决策影响范围
        - 相关的历史讨论
        - 其他需要考虑的因素