labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        感谢您提出问题！请填写详细信息以便社区更好地帮助您。
        
        > 💡 **提示**: 如果是明确的Bug，请考虑使用 [Issue报告](https://github.com/nickrunning/wechat-selkies/issues/new/choose)
  
  - type: textarea
    id: problem-description
    attributes:
      label: 📋 问题描述
      description: 详细描述您遇到的问题或需要帮助的地方
      placeholder: |
        请详细描述：
        - 您想要实现什么？
        - 遇到了什么问题？
        - 期望的结果是什么？
    validations:
      required: true
  
  - type: checkboxes
    id: attempted-solutions
    attributes:
      label: 🔍 已尝试的解决方案
      description: 请勾选您已经尝试过的方法
      options:
        - label: 已阅读项目README文档
        - label: 已搜索现有的Issues和讨论
        - label: 已尝试重启容器
        - label: 已检查Docker日志
        - label: 已尝试清除浏览器缓存
        - label: 已检查网络连接
        - label: 已尝试其他浏览器
  
  - type: dropdown
    id: operating-system
    attributes:
      label: 🖥️ 操作系统
      description: 您使用的操作系统
      options:
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - Debian 11
        - Debian 12
        - CentOS 7
        - CentOS 8
        - Rocky Linux 8
        - Rocky Linux 9
        - Windows 10
        - Windows 11
        - macOS
        - 其他（请在附加信息中说明）
    validations:
      required: true
  
  - type: input
    id: docker-version
    attributes:
      label: 🐳 Docker版本
      description: 运行 `docker --version` 的输出
      placeholder: 例如：Docker version 24.0.6, build ed223bc
    validations:
      required: true
  
  - type: input
    id: compose-version
    attributes:
      label: 🔧 Docker Compose版本
      description: 运行 `docker compose version` 的输出
      placeholder: 例如：Docker Compose version v2.21.0
    validations:
      required: true
  
  - type: dropdown
    id: browser
    attributes:
      label: 🌐 浏览器
      description: 您使用的浏览器
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - 其他（请在附加信息中说明）
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 重现步骤
      description: 详细说明如何重现这个问题
      placeholder: |
        1. 执行命令：...
        2. 打开浏览器访问：...
        3. 点击：...
        4. 看到问题：...
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: 📋 相关日志
      description: 请提供相关的Docker日志或错误信息
      placeholder: |
        粘贴 `docker logs <container-name>` 的输出
        或其他相关的错误信息
      render: shell
  
  - type: textarea
    id: configuration
    attributes:
      label: ⚙️ 配置信息
      description: 请提供相关的配置文件内容（如有修改）
      placeholder: |
        如果您修改了docker-compose.yml或其他配置文件，
        请粘贴相关部分（注意遮盖敏感信息）
      render: yaml
  
  - type: textarea
    id: additional-context
    attributes:
      label: 📝 附加信息
      description: 其他可能有助于解决问题的信息
      placeholder: |
        - 网络环境（是否使用代理、VPN等）
        - 最近的变更或更新
        - 其他相关的系统信息
        - 截图或视频（如适用）